### ISSUE TITLE
Reboot persistence

### ISSUE THREAD

**Issue by BenSegal855** [ud-cis-discord/SageV2#152]
Currently when Sage reboots, no information about the current state of Sage is saved. Here are some things that should sit in a mongo document and be updated as stuff changes so Sage can return to the same state as before a restart. 
- [x] status
- [x] Status should show version number for 1m after bootup
- [x] Enabled/disabled commands
- [ ] Probably other stuff so add more later

**Comment by joshualyon7** [comment]
@BenSegal855 release ready now, right?

**Comment by joshualyon7** [comment]
Closing because merged
