### ISSUE TITLE
Give Sage slash commands 

### ISSUE THREAD

**Issue by sage-ud** [ud-cis-discord/SageV2#183]
- [x] Create new command handler
- [x] Switch over existing commands to slash commands

- [x] #233
- [x] #234 
- [x] #235 
- [x] #236 
- [x] #237 
- [x] #238
- [x] #239

<sub>Created by Josh via Sage</sub>

**Comment by joshualyon7** [comment]
This has been made more important as of https://support-dev.discord.com/hc/en-us/articles/4404772028055
