### ISSUE TITLE
Actually deal with members who have left

### ISSUE THREAD

**Issue by BenSegal855** [ud-cis-discord/SageV2#210]
Currently, if a user leaves the server the only thing that happens is the leave gets logged. This can cause a few issues as their discord id is still present in the database and they cant re-join if they want to. Deleting the whole document would cause some issues. First, the user would have to be re-onboarded in order to join again. They also would not receive their old roles via the role handler and would loose their level progress. The solution is simple, remove their discord id from their user document but keep everything else. This would allow the user to re-verify using the same hash they used the first time and would keep all their role, level, and enrollment data so they loose nothing when they re-join.

**Comment by joshualyon7** [comment]
Fixed with #229
