### ISSUE TITLE
Revamp Rules

### ISSUE THREAD

**Issue by renross** [ud-cis-discord/SageV2#226]
Mod Mail? 
Rules "verification" (buttons, reactions, keywords, etc.)

**Comment by BenSegal855** [comment]
> Mod Mail?
Open a private thread?

**Comment by sbrugel** [comment]
> Open a private thread?

Could make it so one command (let's call it /report) takes in no arguments, but opens a thread containing only the command sender and all admins, then the sender can enter in their concerns. Or possibly, have one argument for the concern, and once the thread is opened, Sage sends in the concern the user has after adding the admin and sender to the thread.

Potentially, we could make another that is anonymous (/anonreport), and thus takes in a parameter with the concerns, then opens a thread only the admins can see, with Sage sending a message to the thread with the concern.
